# Generated by Django 4.2.4 on 2023-08-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profiel_pic',
            new_name='profile_pic',
        ),
    ]
